Sprint 2
microservices-course-itmo/parser-common-api pull request #5
Opened 2020-10-05 17:51 UTC by Gollut

2020-10-05 19:19 UTC, andrsuh commented on src/main/resources/application-common-parser-api.properties
> +parser.common.api.topic-name=message-from-parser-topic-name
@shinehlina

2020-10-05 19:27 UTC, andrsuh commented on src/main/resources/application-common-parser-api.properties
> +parser.common.api.topic-name=message-from-parser-topic-name
suggest renaming to `parser-wine-position-parsed-events`

2020-10-05 19:30 UTC, andrsuh commented on src/main/resources/application-common-parser-api.properties
> +parser.common.api.topic-name=message-from-parser-topic-name
`parser` - the common names of the services-group
`wine-position-parsed` - the name of the event published once the position is parsed
`events` - the type of the message (there are two types: event and command)

2020-10-05 19:30 UTC, andrsuh commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +    ORANGE = 3;
SPARKLING?

2020-10-05 19:31 UTC, andrsuh commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +    ORANGE = 3;
as a sparkling wine can be rose in same time maybe worth considering some special flag?

2020-10-05 20:45 UTC, vadzz-dev commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +    ORANGE = 3;
Looks like a question for BA. They sent us a document with all required fields

2020-10-06 10:55 UTC, shinehlina requested changes

2020-10-06 10:55 UTC, shinehlina commented on pom.xml
> +                                        ${project.basedir}/target/generated-sources/protobuf
Лучше кладите не в тагджет, а к обычным классам (как demo-api)

2020-10-06 10:55 UTC, shinehlina commented on src/main/java/com/wine/to/up/parser/common/api/ParserCommonApiProperties.java
> +@ConfigurationProperties("parser.common.api")
Это точно префикс? 
`@ConfigurationProperties(prefix = "demo.service.api")`

2020-10-06 10:55 UTC, shinehlina commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +  int32 discount = 10;
Давайте хранить пару old_price + new_price. С discount может быть проблема на несколько рублей

2020-10-06 10:55 UTC, shinehlina commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +  string grape_sort = 14;
Кстааати, @andrsuh под этой стрингой хранится список виноградов или один основной?

2020-10-06 10:55 UTC, shinehlina commented on src/main/resources/application-common-parser-api.properties
> +parser.common.api.topic-name=message-from-parser-topic-name
Согласна

2020-10-06 13:58 UTC, Gollut commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +  int32 discount = 10;
Мы так и делали, но БА наанализировали с discount. Поговорим с ними на этот счет

2020-10-06 14:18 UTC, MaximKuznetsov17 commented on src/main/java/com/wine/to/up/parser/common/api/ParserCommonApiProperties.java
> +@ConfigurationProperties("parser.common.api")
Да, оба варианта валидны. Тем более, я уже успел попробовать оба примера использования этой аннотации - ни один не спасает(
Но я потом всё-таки добавлю указание чему мы присваиваем значение "demo.service.api"

2020-10-06 17:52 UTC, vadzz-dev commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +  string grape_sort = 14;
![image](https://user-images.githubusercontent.com/15704718/95240940-c48f6780-0815-11eb-91c1-b4235d347254.png)
у бизнес аналитиков это выглядит так

2020-10-07 17:18 UTC, andrsuh commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +    ORANGE = 3;
I know better :)

2020-10-07 17:19 UTC, andrsuh commented on pom.xml
> +                                        ${project.basedir}/target/generated-sources/protobuf
обяяяяязательно

2020-10-07 17:20 UTC, andrsuh commented on src/main/java/com/wine/to/up/parser/common/api/ParserCommonApiProperties.java
> +@ConfigurationProperties("parser.common.api")
не понял, почему не спасает?

2020-10-07 17:20 UTC, andrsuh commented on src/main/java/com/wine/to/up/parser/common/api/ParserCommonApiProperties.java
> +@ConfigurationProperties("parser.common.api")
вообще ничего не понял

2020-10-07 17:21 UTC, andrsuh commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +  int32 discount = 10;
старая-новая цена обязательна

2020-10-07 17:21 UTC, andrsuh commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +  string grape_sort = 14;
я бы, конечно сделал массив, че за кокатенации

2020-10-07 19:15 UTC, MaximKuznetsov17 commented on src/main/java/com/wine/to/up/parser/common/api/ParserCommonApiProperties.java
> +@ConfigurationProperties("parser.common.api")
@andrsuh Я тоже не понимаю почему не спасает, но такая история не только у меня локально была, но и у моего коллеги.

2020-10-09 17:42 UTC, SShevchik commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +    ORANGE = 3;
Это все цвета вина? Потому что их больше на самом деле

2020-10-09 17:42 UTC, SShevchik commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +    SWEET = 3;
Это конечный набор видов вин по сахару?

2020-10-09 18:30 UTC, Gollut commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +    SWEET = 3;
Насколько конечный - это вопрос к БА, репо синхронизируется с их документом

2020-10-09 18:38 UTC, Re1199 commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +    ORANGE = 3;
Мы для упрощения и оранжевое пока убрали, только 3 основных оставили

2020-10-09 18:39 UTC, Re1199 commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +    SWEET = 3;
остальные можно свести к этим 4, эти основные

2020-10-09 20:25 UTC, vadzz-dev commented on pom.xml
> +                                        ${project.basedir}/target/generated-sources/protobuf
Сделано

2020-10-09 20:25 UTC, vadzz-dev commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +    ORANGE = 3;
Добавил флаг

2020-10-09 20:25 UTC, vadzz-dev commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +  int32 discount = 10;
Готово

2020-10-09 20:25 UTC, vadzz-dev commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +  string grape_sort = 14;
Переделали на масив

2020-10-10 11:22 UTC, shinehlina requested changes

2020-10-10 11:22 UTC, shinehlina commented on src/main/java/com/wine/to/up/parser/common/api/schema/UpdateProducts.java
> +public final class UpdateProducts {
Это класс, который сгенерился, добавьте его в игнор

2020-10-10 11:22 UTC, shinehlina commented on src/main/java/com/wine/to/up/parser/common/api/ParserCommonApiProperties.java
> +    @Value("${parser.common.api.parser-wine-position-parsed-events}")
Нам бы хотелось, как в demo-api, через префикс

2020-10-10 13:07 UTC, shinehlina commented on src/main/java/com/wine/to/up/parser/common/api/ParserCommonApiProperties.java
> +    @Value("${parser.common.api.parser-wine-position-parsed-events}")
Хотя пофиг

2020-10-10 13:08 UTC, shinehlina commented
Добавьте ещё имя магазина в дто

2020-10-10 20:08 UTC, AfanasievYuriy approved these changes

2020-10-10 20:57 UTC, merged

2020-10-12 15:28 UTC, SSyrova commented on src/main/java/com/wine/to/up/parser/common/api/schema/update_products.proto
> +    SWEET = 3;
А кто будет описывать логику сведения к основным? Нужен тогда стандарт